//! Exact status-code contract over pinned deterministic conformance vectors.
//!
//! The corpus is generated by a fixed `encypherai/c2pa-conformance-suite`
//! commit. The test invokes only this repository's CLI and performs no network
//! access or runtime vector generation.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;
use sha2::{Digest, Sha256};

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors/conformance")
}

fn index() -> Value {
    let path = corpus_dir().join("corpus.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("parse {}: {error}", path.display()))
}

fn vectors(index: &Value) -> &Vec<Value> {
    index["vectors"].as_array().expect("vectors array")
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hex = String::with_capacity(64);
    for byte in Sha256::digest(bytes) {
        write!(&mut hex, "{byte:02x}").expect("writing to String cannot fail");
    }
    hex
}

fn expected_codes(expected: &Value, bucket: &str) -> BTreeSet<String> {
    expected[bucket]
        .as_array()
        .unwrap_or_else(|| panic!("{bucket} array"))
        .iter()
        .map(|code| code.as_str().expect("status code").to_owned())
        .collect()
}

fn observed_codes(report: &Value, bucket: &str) -> BTreeSet<String> {
    report["validation_results"]["activeManifest"][bucket]
        .as_array()
        .expect("validation result bucket")
        .iter()
        .map(|item| item["code"].as_str().expect("status code").to_owned())
        .collect()
}

fn verify(vector: &Value) -> (i32, Value) {
    let output = Command::new(env!("CARGO_BIN_EXE_encypher-c2pa"))
        .arg("verify")
        .arg(corpus_dir().join(vector["path"].as_str().expect("path")))
        .arg("--mime")
        .arg(vector["mime_type"].as_str().expect("mime_type"))
        .arg("--time")
        .arg(
            vector["fixed_validation_time"]
                .as_str()
                .expect("fixed_validation_time"),
        )
        // The corpus contract covers validation statuses, not the SDK's
        // independently refreshed packaged trust snapshot.
        .arg("--no-default-trust")
        .arg("--json")
        .output()
        .expect("run Encypher CLI");
    let code = output.status.code().expect("CLI exit code");
    assert!(
        matches!(code, 0 | 2),
        "{}: CLI exited {code}: {}",
        vector["id"],
        String::from_utf8_lossy(&output.stderr)
    );
    let envelope: Value = serde_json::from_slice(&output.stdout).expect("CLI JSON envelope");
    (code, envelope["manifest_report"].clone())
}

#[test]
fn corpus_is_immutable_licensed_and_self_contained() {
    let index = index();
    assert_eq!(index["source"]["commit"].as_str().unwrap().len(), 40);
    assert_eq!(index["source"]["license"], "Apache-2.0");
    let license = corpus_dir().join(index["source"]["license_file"].as_str().unwrap());
    assert!(
        license.is_file(),
        "missing source license {}",
        license.display()
    );

    for vector in vectors(&index) {
        let path = corpus_dir().join(vector["path"].as_str().expect("path"));
        let bytes =
            std::fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        assert_eq!(
            bytes.len() as u64,
            vector["size"].as_u64().expect("size"),
            "{}: size drift",
            vector["id"]
        );
        assert_eq!(
            sha256_hex(&bytes),
            vector["sha256"].as_str().expect("sha256"),
            "{}: content drift",
            vector["id"]
        );
    }
}

#[test]
fn generated_vectors_match_exact_status_contracts() {
    let index = index();
    for vector in vectors(&index) {
        let expected = &vector["expected"];
        let (exit_code, report) = verify(vector);
        assert_eq!(
            exit_code,
            expected["exit_code"].as_i64().expect("exit_code") as i32,
            "{}: exit code",
            vector["id"]
        );
        assert_eq!(
            report["validation_state"], expected["validation_state"],
            "{}: validation state",
            vector["id"]
        );
        assert_eq!(
            report["manifests"].as_object().expect("manifests").len(),
            expected["manifest_count"].as_u64().expect("manifest_count") as usize,
            "{}: manifest count",
            vector["id"]
        );
        for (bucket, field) in [
            ("success", "success_codes"),
            ("failure", "failure_codes"),
            ("informational", "informational_codes"),
        ] {
            assert_eq!(
                observed_codes(&report, bucket),
                expected_codes(expected, field),
                "{}: {bucket} status codes",
                vector["id"]
            );
        }
    }
}
